//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace websitesiprojesi60820222.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Settings
    {
        public int ID { get; set; }
        public Nullable<int> sayfadakiurunsayisi { get; set; }
        public string telefon { get; set; }
        public Nullable<int> anasayfadakiurunsayisi { get; set; }
    }
}
