//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace websitesiprojesi60820222.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Orders
    {
        public int orderID { get; set; }
        public Nullable<System.DateTime> orderDate { get; set; }
        public string orderGroupGUID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual tbl_Users tbl_Users { get; set; }
    }
}
